# Generated by Django 5.2.6 on 2025-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('escalated', 'Escalado'), ('assigned', 'Asignado'), ('paused', 'Pausado'), ('resumed', 'Reanudado'), ('resolved', 'Resuelto')], max_length=20)),
                ('level', models.IntegerField(help_text='Nivel de escalamiento')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el escalamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], help_text='Prioridad del ticket', max_length=10)),
                ('level', models.IntegerField(help_text='Nivel de escalamiento (1, 2, 3, etc.)')),
                ('hours_to_escalate', models.IntegerField(help_text='Horas sin respuesta antes de escalar')),
                ('notification_template', models.TextField(blank=True, help_text='Template personalizado para la notificación')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'priority', 'level'],
            },
        ),
        migrations.CreateModel(
            name='EscalationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Si el escalamiento automático está habilitado')),
                ('business_hours_only', models.BooleanField(default=True, help_text='Solo escalar en horario laboral')),
                ('business_start_hour', models.IntegerField(default=9, help_text='Hora de inicio del horario laboral (0-23)')),
                ('business_end_hour', models.IntegerField(default=17, help_text='Hora de fin del horario laboral (0-23)')),
                ('business_days', models.CharField(default='1,2,3,4,5', help_text='Días laborales (1=Lunes, 7=Domingo)', max_length=20)),
                ('max_escalation_level', models.IntegerField(default=3, help_text='Nivel máximo de escalamiento')),
                ('auto_assign_on_escalation', models.BooleanField(default=True, help_text='Asignar automáticamente al escalar')),
                ('pause_on_response', models.BooleanField(default=True, help_text='Pausar escalamiento cuando hay respuesta')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enviar notificaciones por email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Escalamiento',
                'verbose_name_plural': 'Configuraciones de Escalamiento',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del filtro', max_length=100)),
                ('filter_data', models.JSONField(help_text='Datos del filtro en formato JSON')),
                ('is_default', models.BooleanField(default=False, help_text='Si es el filtro por defecto del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_response_at', models.DateTimeField(blank=True, help_text='Última vez que se respondió al ticket', null=True)),
                ('escalation_level', models.IntegerField(default=0, help_text='Nivel de escalamiento actual (0=sin escalar)')),
                ('next_escalation_at', models.DateTimeField(blank=True, help_text='Próxima fecha de escalamiento', null=True)),
                ('escalation_paused', models.BooleanField(default=False, help_text='Si el escalamiento está pausado')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
