# Generated by Django 5.2.6 on 2025-09-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa específica (null = regla global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='companies.company'),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='escalate_to',
            field=models.ForeignKey(help_text='Usuario al que escalar', on_delete=django.db.models.deletion.CASCADE, related_name='escalation_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='escalation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tickets.escalationrule'),
        ),
        migrations.AddField(
            model_name='escalationsettings',
            name='company',
            field=models.OneToOneField(blank=True, help_text='Empresa específica (null = configuración global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_settings', to='companies.company'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='companies.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketmessage'),
        ),
        migrations.AlterUniqueTogether(
            name='escalationrule',
            unique_together={('company', 'priority', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='savedfilter',
            unique_together={('user', 'name')},
        ),
    ]
